### ISSUE TITLE
Jbehave agent does not send failure details to RP

### ISSUE THREAD

**Issue by scormaq** [reportportal/agent-java-jbehave#3]
**Summary**
When story failed, agent does not log error details to portal

**Prerequisites**
Used dependencies:
```
'com.epam.reportportal:client-java:3.0.3'
'com.epam.reportportal:commons-model:3.0.0'
'com.epam.reportportal:agent-java-jbehave:3.0.0-BETA-2'
'ch.qos.logback:logback-classic:1.2.3'
'ch.qos.logback:logback-core:1.2.3'
'com.epam.reportportal:logger-java-logback:3.0.0'
```
It seems that code for sending errors is missed in jbehave agent for some reason. For instance, here is code example from testNG agent:
```java
// com.epam.reportportal.testng.BaseTestNGListener
...
    @Override
    public void onTestFailure(ITestResult testResult) {
        testNGService.get().sendReportPortalMsg(testResult);
        testNGService.get().finishTestMethod(Statuses.FAILED, testResult);
    }
...
```
And identical (I believe) step from jbehave agent:
```java
// com.epam.reportportal.jbehave.ReportPortalStoryReporter
...
	@Override
	public void failed(String step, Throwable cause) {
		JBehaveUtils.finishStep(Statuses.FAILED);
	}
...
```
and there neither sending errors inside the code.

**Comment by avarabyeu** [comment]
@scormaq right. Do you thing we have to put the same functionality?

**Comment by scormaq** [comment]
Hi @avarabyeu - in my opinion it will be very useful to see log messages and stack traces directly in Report Portal (instead of switching between RP and Jenkins/etc during test analysis).

Other agents already can send logs, for JBehave we have to implement this feature manually in any way - but it will be cool to be supported out-of-the-box.

**Comment by avarabyeu** [comment]
@scormaq OK. Not sure if i have time for that this week. Feel free to fix it by yourself and make PR if you want it asap

**Comment by avarabyeu** [comment]
Fixed.
