### ISSUE TITLE
Multithreading support- JBehave Agent

### ISSUE THREAD

**Issue by itramya333** [reportportal/agent-java-jbehave#62]
We have configured threads in Jenkin builds. If we execute a build with -Djbehave.execution.threads=4, the results are showing wrong.

Even when the build passes, its showing few scenarios have failed and not showing the correct total scenarios.

First build is with thread=4
Second build is with thread=1

Total Passed Failed
7            4      2   ---> Build1
10         10          ----> Build 2

I am using the latest JBehave agent version 5.1.2

com.epam.reportportal
agent-java-jbehave
5.1.2
Does reportportal supports multithreads

**Comment by HardNorth** [comment]
@itramya333 I wasn't able to reproduce your issue, could you please explain how you run your code?

**Comment by HardNorth** [comment]
Abndoned
