### ISSUE TITLE
406 error was returned when previous test didn’t start with STORY CANCELLED log

### ISSUE THREAD

**Issue by irina-maruga** [reportportal/agent-java-jbehave#7]
18/02/2018
20:13:20 io.reactivex.exceptions.OnErrorNotImplementedException: Report Portal returned error 
20:13:20 Status code: 406 
20:13:20 Status message: Not Acceptable 
20:13:20 Error Message: Finish test item is not allowed.

Please find the log in attachment
[406-error-18-02-2018.txt](https://github.com/reportportal/agent-java-jbehave/files/1758335/406-error-18-02-2018.txt)

**Comment by evjlobanova** [comment]
@irina-maruga hello! Could you please say what versions of RP and agent do you use?

**Comment by irina-maruga** [comment]
jbehave agent version 4.0.0-BETA-1

**Comment by evjlobanova** [comment]
@pbortnik

**Comment by pbortnik** [comment]
@irina-maruga 
Hello, could you please share a little project how to reproduce the issue?

**Comment by irina-maruga** [comment]
we updated to 4.0 and haven't faced this issue yet

**Comment by evjlobanova** [comment]
@irina-maruga could I close this issue?

**Comment by irina-maruga** [comment]
we are not going to use 4.0.0-BETA-1. But I do not know yet if it is applicable for 4.0

**Comment by avarabyeu** [comment]
closed. Please, submit new one in case you still have an issue
