### ISSUE TITLE
sendStackTraceToRP throws NullPointerException

### ISSUE THREAD

**Issue by irina-maruga** [reportportal/agent-java-jbehave#8]
sendStackTraceToRP(final Throwable cause) method throws NullPointerException in case if throwable is like this:
failed(step, new Throwable(errorCount + " of soft assertions were failed"));
()
getCause here reryrns null (cause==this)
if (cause != null) {
     rq.setMessage(getStackTraceAsString(cause.getCause()));
}
It worked properly in beta

**Comment by avarabyeu** [comment]
@irina-maruga could you please send as tracktrace?
